### DISCUSSION TITLE
meross msl 420

### DISCUSSION THREAD

**Discussion by Th4n4tos** [krahabb/meross_lan#131] [General]
Hello, I am a complete beginner
With your Meros Lan I was able to integrate the meross msl 420 (https://meross.com/Detail/22/Smart%20Wi-Fi%20Ambient%20Light) into home assistant.
Can you tell me how I can set the RGB value for automations?
I try  for example  rgb_color: [255,0,0] in the /config/automations.yaml but it doesn't work

great work

**Comment by krahabb** [comment]
Hello @Th4n4tos ,
I'm not an expert on how to manage lights in automations but the first thing to test is to make sure you can manage the msl420 correctly from the standard lovelace panel.
If it happens so, then you could move to build your automation by maybe copying some other examples.
If still not working, please post your complete automation snippet for the msl420 so I could test and check it a bit

**Comment by Th4n4tos** [comment]
Hello krahabb,

the Meros MSL 420 is correctly integrated in the lovelace and can be addressed with brightness, color temperature and color.
With automation, the value for the brightness can be transferred, but no color values.

This is my snippet for the /config/automations.yaml thats works

```
- id: '1639382415638'
  alias: Meross on
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: my device_id
    entity_id: my entity_id
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: my device_id
    entity_id: my entity_id
    domain: light
    brightness_pct: 60
  mode: single
```
I tried the following for the color setting, but it doesn't work

```
- id: '1639382415638'
  alias: Meross on
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: my device_id
    entity_id: my entity_id
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: my device_id
    entity_id: my entity_id
    domain: light
    brightness_pct: 60
    rgb_color: [0,255,0]
  mode: single
```

**Comment by Th4n4tos** [comment]
I found it, it has to be addressed via a service.
```
- id: '1639382415638'
  alias: Meross on
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: my device_id
    entity_id: my entity_id
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 0
      - 0
    target:
      entity_id:
      - light.meross
  mode: single
```
the meross msl 420 works perfectly with your meros_lan

thanks a lot and best greetings
