### DISCUSSION TITLE
Homeassistnt - change msl120d RGB colors with a gradient

### DISCUSSION THREAD

**Discussion by lor74** [krahabb/meross_lan#350] [Q&A]
Hi, 
I am quite newbie in homeassistant, I have bought a Meross Light RBG Bulb and I have succesfully create an automation for color switch using scenes.
I have create different scenes with differnet colours and then create an automation that every 10 seconds change the scene starting 30 minutes after sunset

```
alias: XMAS Lamp Light
description: 
trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"
condition: []
action:
  - repeat:
      sequence:
        - service: scene.turn_on
          target:
            entity_id: scene.lampada_terrazzo_colore_1
          metadata: {}
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
        - service: scene.turn_on
          target:
            entity_id: scene.terrazzo_colore_11
          metadata: {}
        - delay:
            hours: 0
            minutes: 0
            seconds: 10
            milliseconds: 0
.......

```
It's possible to change the colours smoothly (eg. like changing the colours with slide bar)?

Thanks :)

**Comment by krahabb** [comment]
Hello @lor74,
I don't really know for sure but I think you might take a look at [adaptive lighting](https://github.com/basnijholt/adaptive-lighting) which could give you direct control of transitions.
Meross bulbs/lamps atcually have some native transition features (at least some hw/fw combo) but I don't know how they could work so I cannot implement a native feature management in meross_lan.

**Comment by lor74** [comment]
Hi Krahabb thanks for your suggestion. 
In the meantime I have changed the logic of automation using light.turn_on service.
I have create an input_select withe several colours and than use this to change the bulb color. 
The light.turn_on service has also a transition parameter but it seems not working on Meross bulb, changing the value didn't change the behaviour of color change.
Here it is the new automation created follwong this post
[https://community.home-assistant.io/t/light-value-rotating-rainbow-effect-transition-etc/332116](url)

```
alias: XMAS Lamp Light V2.0
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"
condition: []
action:
  - repeat:
      sequence:
        - service: light.turn_on
          target:
            device_id: 5cd5474060c9ae06cc5f6405b16798c3
          data:
            color_name: "{{ states('input_select.colors') }}"
            transition: 10
        - service: input_select.select_next
          target:
            entity_id: input_select.colors
          data:
            cycle: true
      until:
        - condition: time
          before: "02:00:00"
  - service: light.turn_off
    target:
      device_id: 5cd5474060c9ae06cc5f6405b16798c3
    data: {}
mode: single
```


Now I will try to study the adaptive lighting.

Thanks
