### DISCUSSION TITLE
climate.set_preset_mode : is it meant to be permanent?

### DISCUSSION THREAD

**Discussion by Japtan** [krahabb/meross_lan#527] [Q&A]
Hello,

I own a couple of MTS150 Smart Thermostat Valves. I created the following automation to set them all to "auto" every night at 2 AM. This is because, otherwise, if you manually set a temperature on the valve, it remains fixed indefinitely—unless "auto" mode is enabled again.

```
- id: '1733264260414'
  alias: Radiateur sur auto
  description: ''
  triggers:
  - trigger: time
    at: 02:00:00
  conditions: []
  actions:
  - action: climate.set_preset_mode
    target:
      entity_id:
      - climate.radiateur_bureau
      - climate.radiateur_x
      - climate.radiateur_y
      - climate.radiateur_chambre_parents
      - climate.radiateur_douche
      - climate.radiateur_fenetre_cuisine
      - climate.radiateur_hall_d_entree
      - climate.radiateur_mur_cuisine
      - climate.radiateur_salle_de_bain
      - climate.radiateur_living_room_gauche
      - climate.radiateur_living_room_coin_gauche
      - climate.radiateur_living_room_coin_droite
      - climate.radiateur_living_room_droite
    data:
      preset_mode: auto
  mode: single`

```
The issue is that after this automation runs, it becomes impossible to change the target temperature in Home Assistant or even in the Meross app. Whenever I try to change the temperature, the valve switches to manual mode, but almost immediately, the change is reverted, and the mode is set back to auto.

Is this the intended behavior?
Is there a way to "release" the set_preset_mode command so that manual changes are allowed afterward?

Thanks for your help!
