### ISSUE TITLE
Beta firmware (6.1.10) connection issue

### ISSUE THREAD

**Issue by ffrog8** [krahabb/meross_lan#219]
Similar to https://github.com/krahabb/meross_lan/issues/181 Mss 310  smart plugs not resetting their energy usage to 0 at midnight. I raised the issue with meross - they said they had a beta firmware that should resolve the issue.
They uploaded it to one of my plugs and how HA can't interface to it anymore.

Device info: mss310 6.0.0
by Meross: Firmware: 6.1.10

## Configuration

```yaml

{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2022.9.0",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Australia/Adelaide",
    "os_name": "Linux",
    "os_version": "4.4.59+",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "2.6.2",
      "requirements": []
    },
    

```

## Debug log

```text

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/config_flow.py:199
Integration: Meross LAN ([documentation](https://github.com/krahabb/meross_lan), [issues](https://github.com/krahabb/meross_lan/issues))
First occurred: 8:30:12 PM (3 occurrences)
Last logged: 8:32:25 PM

Error (Server disconnected) configuring meross device (host:<ip>)





```
