### ISSUE TITLE
very high latency

### ISSUE THREAD

**Issue by dannyneup** [krahabb/meross_lan#313]
## Version of the custom_component
newest

## Configuration

```yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

```

## Describe the bug
Hi, 
there is a high latency when using my ms210 with this integration. This does not occur when using the cloud integration. 
The latent varies between 0 and 11 seconds.

## Debug log

[home-assistant_meross_lan_2023-09-05T11-32-21.068Z.log](https://github.com/krahabb/meross_lan/files/12523123/home-assistant_meross_lan_2023-09-05T11-32-21.068Z.log)
