### ISSUE TITLE
2024.5.0 - blocking call to import_module detected

### ISSUE THREAD

**Issue by RobertD502** [krahabb/meross_lan#427]
## Version of the custom_component

`5.0.4`
## Configuration

```yaml

Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 2:49:51 PM (4 occurrences)
Last logged: 2:49:51 PM

Detected blocking call to import_module inside the event loop by custom integration 'meross_lan' at custom_components/meross_lan/meross_device.py, line 472: module = import_module( (offender: /config/custom_components/meross_lan/meross_device.py, line 472: module = import_module(), please create a bug report at https://github.com/krahabb/meross_lan/issues

```

## Describe the bug
Starting with Home Assistant 2024.5.0 beta, the warning seen above is being logged. It is referring to the following code in `meross_device.py`:

```python
        for namespace, init_descriptor in MerossDevice.ENTITY_INITIALIZERS.items():
            if namespace in ability:
                with self.exception_warning("initializing namespace:%s", namespace):
                    module = import_module(
                        init_descriptor[0], "custom_components.meross_lan"
                    )
                    getattr(module, init_descriptor[1])(self)
```

[Related Home Assistant Core PR](https://github.com/home-assistant/core/pull/114488)
 
## Debug log

```text

N/A

```
