### ISSUE TITLE
5.1.0 breaks color_temp with MSL120 light bulbs

### ISSUE THREAD

**Issue by markus-korbel** [krahabb/meross_lan#440]
When using the service light.turn_on from my automations for hallways I pass along the color_temp during the day (setting it to dark red in the middle of the night).

When updating to 5.1.0 the lights do not turn on when the color_temp parameter is present. If I remove it and only have brightness (those are the only two settings passed), the light turns on fine.

Example from on of my automations:

```
service: light.turn_on
data:
  brightness_pct: 70
  color_temp: 475
target:
  entity_id: light.landing_light
```

I reverted back to 5.0.4 and the automations work fine again. I didn't see any errors when using 5.1.0, the actions performed fine, the lights just won't turn on. If you require a debug run let me know and I will update to the new version again, for now I will remain on the older.
