### ISSUE TITLE
MSS510X doesn't seem to work

### ISSUE THREAD

**Issue by ZachMayry** [krahabb/meross_lan#77]
## Version of the custom_component
2.2.1

## Configuration

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  broker: "192.168.1.3"
  port: 1883
```

## Describe the bug
It seems that when Meross LAN is configured in MQTT or Auto mode the switch will immediately start blinking with a connection issue. If I switch it to HTTP mode, the switch works and I can control HA with it but my automations no longer work. After some time it'll give the same  connection issue. Usually once the automation finally kicks in. Automations that trigger the events from the switch work, just not ones that trigger the switch.

I have other 510k/s switches that work just fine as well as 2 550x and 560x

It seems that no matter how hard I try to get this device to use my local broker that it keeps on defaulting back to mqtt-us.meross.com:443

The image below shows a working one and the not working one.
I'm wondering if I should return the switch and get a new one and not apply any firmware updates. 
![image](https://user-images.githubusercontent.com/12666484/133196619-5115e5ff-b61f-43be-bf67-403c93a899de.png)
## Debug log

```text
[36m2021-09-13 23:43:02 DEBUG (MainThread) [custom_components.meross_lan] MerossHttpClient(192.168.3.116): HTTP Response ({"header":{"messageId":"49f085b274a34ce99f5c06cf54b6d9f0","namespace":"Appliance.System.All","method":"ERROR","payloadVersion":1,"from":"/appliance/2103031270852255853448e1e9600f7e/publish","timestamp":1631594582,"timestampMs":750,"sign":"2a4c23ee6437d46ca38ef12484ca5f93"},"payload":{"error":{"code":5001,"detail":"sign error"}}}
)[0m
[36m2021-09-13 23:43:02 DEBUG (MainThread) [custom_components.meross_lan] Key error on 192.168.3.116 (GET:Appliance.System.All) -> retrying with key-reply hack[0m
```

after I forced the gateway to use my local mqtt broker a second time after it was already set up, I get these logs
```text
[36m2021-09-14 00:00:54 DEBUG (MainThread) [custom_components.meross_lan] MerossApi: MQTT RECV device_id:(2103038929302755853448e1e9601b88) method:(ERROR) namespace:(Appliance.System.All)[0m
[36m2021-09-14 00:00:54 DEBUG (MainThread) [custom_components.meross_lan] MerossApi: MQTT RECV device_id:(2103038929302755853448e1e9601b88) method:(ERROR) namespace:(Appliance.System.All)[0m
```
